// @ts-nocheck
// Generated by personalize-harness-pi. Edit the Harness Profile artifact first, then regenerate.
import { existsSync, readFileSync, realpathSync, statSync } from "node:fs";
import { dirname, isAbsolute, join, relative, resolve, sep } from "node:path";
import type { ExtensionAPI } from "@earendil-works/pi-coding-agent";

type CheckTiming = "afterWrite" | "agentEnd" | "beforeGit" | "manual";
type HarnessPosture = "advisory" | "blocking";

type CommandSpec = {
  id: string;
  extensions: string[];
  command: string;
  args: string[];
  timeoutMs: number;
};

type CommandResult = { ok: boolean; stdout: string; stderr: string; error?: string };

type LintSpec = CommandSpec & { posture: HarnessPosture };
type SyntaxSpec = CommandSpec & { posture: "blocking" };

type ProjectCheckSpec = {
  id: string;
  command: string;
  args: string[];
  cwd: string;
  timeoutMs: number;
  triggerExtensions: string[];
  triggerGlobs: string[];
  timing: CheckTiming;
  posture: HarnessPosture;
  label?: string;
};

type ScenarioCheckSpec = ProjectCheckSpec & { reason: string };

type SafetyRuleSpec = {
  id: string;
  tools: string[];
  match?: string;
  paths?: string[];
  operation: string;
  reason: string;
  posture: "blocking" | "advisory";
};

type ArchitectureGuidanceSpec = {
  relativePath: string;
  label: string;
  appliesTo: string;
  mode: "full" | "reference" | "scoped";
};

type GuidanceSpec = {
  relativePath: string;
  appliesTo: string;
  label: string;
};

type HarnessProfile = {
  sourceArtifact: string;
  targetRepo: string;
  outputPath: string;
  syntaxChecks: SyntaxSpec[];
  formatters: CommandSpec[];
  lintChecks: LintSpec[];
  projectChecks: ProjectCheckSpec[];
  scenarioChecks: ScenarioCheckSpec[];
  safetyRules: SafetyRuleSpec[];
  guidanceFiles: GuidanceSpec[];
  architectureGuidance: ArchitectureGuidanceSpec[];
  promptAdvisories: string[];
  gitReminder: {
    enabled: boolean;
    posture: HarnessPosture;
    text: string;
  };
  gitPreflight: {
    enabled: boolean;
    posture: HarnessPosture;
    text: string;
    runProjectChecks: boolean;
  };
  smokeTests: {
    loadSmoke: boolean;
    isolatedLoadSmoke: boolean;
    syntaxDryChecks: string[];
    safetyDryChecks: string[];
    projectCheckDryChecks: string[];
    manualScenarioListing: boolean;
    guidanceDry: boolean;
  };
  skipped: Array<{ area: string; reason: string }>;
};

const PROFILE: HarnessProfile = {
  "sourceArtifact": "wiki/raw/personal-harness-pi-profile.md",
  "targetRepo": "/home/james/symphony",
  "outputPath": ".pi/extensions/personal-harness.ts",
  "syntaxChecks": [
    {
      "id": "python-py-compile",
      "extensions": [
        ".py"
      ],
      "command": "python3",
      "args": [
        "-m",
        "py_compile",
        "{file}"
      ],
      "timeoutMs": 10000,
      "posture": "blocking"
    },
    {
      "id": "json-jq",
      "extensions": [
        ".json"
      ],
      "command": "jq",
      "args": [
        ".",
        "{file}"
      ],
      "timeoutMs": 10000,
      "posture": "blocking"
    },
    {
      "id": "javascript-node-check",
      "extensions": [
        ".js",
        ".mjs",
        ".cjs"
      ],
      "command": "node",
      "args": [
        "--check",
        "{file}"
      ],
      "timeoutMs": 10000,
      "posture": "blocking"
    },
    {
      "id": "shell-bash-n",
      "extensions": [
        ".sh",
        ".bash",
        ".zsh"
      ],
      "command": "bash",
      "args": [
        "-n",
        "{file}"
      ],
      "timeoutMs": 10000,
      "posture": "blocking"
    }
  ],
  "formatters": [],
  "lintChecks": [
    {
      "id": "python-ruff-check",
      "extensions": [
        ".py"
      ],
      "command": "ruff",
      "args": [
        "check",
        "{file}"
      ],
      "timeoutMs": 10000,
      "posture": "advisory"
    }
  ],
  "projectChecks": [
    {
      "id": "frontend-tsc",
      "command": "pnpm",
      "args": [
        "exec",
        "tsc",
        "--noEmit"
      ],
      "cwd": "web/frontend",
      "timeoutMs": 120000,
      "triggerExtensions": [
        ".ts",
        ".tsx"
      ],
      "triggerGlobs": [
        "web/frontend/**"
      ],
      "timing": "agentEnd",
      "posture": "advisory",
      "label": "Frontend TypeScript typecheck"
    },
    {
      "id": "git-diff-check",
      "command": "git",
      "args": [
        "diff",
        "--check"
      ],
      "cwd": "",
      "timeoutMs": 30000,
      "triggerExtensions": [],
      "triggerGlobs": [],
      "timing": "beforeGit",
      "posture": "advisory",
      "label": "Whitespace check"
    }
  ],
  "scenarioChecks": [
    {
      "id": "frontend-playwright-e2e",
      "command": "pnpm",
      "args": [
        "test:e2e"
      ],
      "cwd": "web/frontend",
      "timeoutMs": 300000,
      "triggerExtensions": [
        ".ts",
        ".tsx"
      ],
      "triggerGlobs": [
        "web/frontend/**"
      ],
      "timing": "manual",
      "posture": "advisory",
      "label": "Frontend Playwright e2e",
      "reason": "Expensive browser suite; current config runs next dev in repo and can overwrite .next, so list only and never auto-run."
    }
  ],
  "safetyRules": [
    {
      "id": "secret-env-write",
      "tools": [
        "write",
        "edit",
        "ast_grep_replace"
      ],
      "paths": [
        ".env",
        "*.env",
        ".env*",
        "**/.env*"
      ],
      "operation": "write env/secret file",
      "reason": "Env files can contain credentials and are gitignored; never write without explicit operator intent.",
      "posture": "blocking"
    },
    {
      "id": "secret-env-read",
      "tools": [
        "read"
      ],
      "paths": [
        ".env",
        "*.env",
        ".env*",
        "**/.env*",
        "../symphony-host.env"
      ],
      "operation": "read secret file",
      "reason": "/home/james/symphony-host.env and .env files must never be printed.",
      "posture": "blocking"
    },
    {
      "id": "secret-env-bash-read",
      "tools": [
        "bash"
      ],
      "match": "(^|[;&|]\\s*)\\s*(cat|less|more|sed|grep|awk|head|tail)\\b[^;&|]*(/home/james/symphony-host\\.env|(^|\\s)(\\.env[^\\s;&|]*|[^\\s;&|]*/\\.env[^\\s;&|]*|[^\\s;&|]*\\.env)(\\s|$))",
      "operation": "read env/secret file via shell",
      "reason": "Shell reads can print secrets; block common readers against /home/james/symphony-host.env and .env-like files.",
      "posture": "blocking"
    },
    {
      "id": "generated-vendor-write",
      "tools": [
        "write",
        "edit",
        "ast_grep_replace"
      ],
      "paths": [
        ".git/**",
        ".venv/**",
        "web/frontend/node_modules/**",
        "web/frontend/.next/**",
        "web/frontend/.next.staging/**",
        "web/frontend/.next.prev/**",
        "__pycache__/**",
        ".pytest_cache/**",
        "runs/**",
        "podium.db",
        "podium.db-*"
      ],
      "operation": "write generated/vendor/runtime data",
      "reason": "Protect dependencies, git metadata, live fallback DB, run logs, and Next build output.",
      "posture": "blocking"
    },
    {
      "id": "live-config-edit",
      "tools": [
        "write",
        "edit",
        "ast_grep_replace"
      ],
      "paths": [
        "bindings.yml",
        "models.yml"
      ],
      "operation": "edit live config",
      "reason": "Bindings and model catalog affect live dispatch/UI behavior; review deliberately.",
      "posture": "advisory"
    },
    {
      "id": "live-systemctl",
      "tools": [
        "bash"
      ],
      "match": "(^|[;&|]\\s*)\\s*(sudo\\s+)?systemctl\\s+(restart|stop|start|reload)\\s+(symphony-host|podium-api|podium-web|telegram-alert@)[^\\s;]*",
      "operation": "mutate live services",
      "reason": "Project docs require James approval before service restart/stop/unit actions.",
      "posture": "blocking"
    },
    {
      "id": "unit-file-touch",
      "tools": [
        "bash"
      ],
      "match": "/etc/systemd/system/(symphony-host|podium-api|podium-web|telegram-alert@)[^\\s;]*\\.service",
      "operation": "touch live systemd unit",
      "reason": "Unit edits require backup, daemon-reload, and operator approval.",
      "posture": "blocking"
    },
    {
      "id": "plane-api-mutation",
      "tools": [
        "bash"
      ],
      "match": "(curl|http|httpx).*(POST|PATCH|DELETE|archive|/archive/).*(plane|PLANE_API|PLANE_API_URL)",
      "operation": "mutate Plane API",
      "reason": "Plane mutations require explicit operator approval even during retirement.",
      "posture": "blocking"
    },
    {
      "id": "destructive-db-log-rm",
      "tools": [
        "bash"
      ],
      "match": "(^|[;&|]\\s*)\\s*(sudo\\s+)?rm\\s+-[A-Za-z]*r?f?[A-Za-z]*\\s+([^;&|]*(podium\\.db|/var/lib/symphony|runs/|/backup/podium)[^;&|]*)",
      "operation": "delete database, backups, or run logs",
      "reason": "Podium DB, backups, and run logs are operational data.",
      "posture": "blocking"
    },
    {
      "id": "generic-rm-rf",
      "tools": [
        "bash"
      ],
      "match": "(^|[;&|]\\s*)\\s*(sudo\\s+)?rm\\s+-[A-Za-z]*r[fA-Za-z]*\\s+(/|\\.\\.|\\.)($|\\s|;)",
      "operation": "destructive recursive delete",
      "reason": "Universal destructive command blocker.",
      "posture": "blocking"
    },
    {
      "id": "alembic-downgrade",
      "tools": [
        "bash"
      ],
      "match": "(^|[;&|]\\s*)\\s*(uv\\s+run\\s+)?alembic\\s+downgrade\\b",
      "operation": "downgrade database schema",
      "reason": "Repo documents forward Alembic revisions; downgrade path is not documented.",
      "posture": "blocking"
    },
    {
      "id": "podium-skills-live-refresh",
      "tools": [
        "bash"
      ],
      "match": "python\\s+-m\\s+web\\.cli\\.podium\\s+skills\\s+refresh(?![^;&|]*--dry-run)",
      "operation": "mutate Podium skill catalog",
      "reason": "Docs require dry-run first; live refresh is operator action.",
      "posture": "advisory"
    },
    {
      "id": "frontend-build-live",
      "tools": [
        "bash"
      ],
      "match": "(^|[;&|]\\s*)\\s*(pnpm\\s+(build|start)|pnpm\\s+exec\\s+next\\s+(build|start))\\b",
      "operation": "build/start frontend outside deploy script",
      "reason": "In-place .next build/start can break live frontend; use deploy script intentionally.",
      "posture": "advisory"
    }
  ],
  "guidanceFiles": [],
  "architectureGuidance": [
    {
      "relativePath": "CONTEXT.md",
      "label": "Symphony domain glossary",
      "appliesTo": ".",
      "mode": "reference"
    },
    {
      "relativePath": "wiki/index.md",
      "label": "Wiki index",
      "appliesTo": ".",
      "mode": "reference"
    },
    {
      "relativePath": "wiki/ROUTING.md",
      "label": "Wiki routing",
      "appliesTo": ".",
      "mode": "reference"
    },
    {
      "relativePath": "web/README.md",
      "label": "Podium web/API runbook",
      "appliesTo": "web/",
      "mode": "reference"
    },
    {
      "relativePath": "docs/adr/0005-replace-plane-with-podium.md",
      "label": "ADR-0005 Podium architecture",
      "appliesTo": "web/",
      "mode": "reference"
    },
    {
      "relativePath": "docs/adr/0006-engine-state-surfaced-by-polling-not-websocket.md",
      "label": "ADR-0006 polling decision",
      "appliesTo": "web/frontend/",
      "mode": "reference"
    },
    {
      "relativePath": "wiki/analyses/symphony-tests-index.md",
      "label": "Symphony validation contract",
      "appliesTo": "tests/",
      "mode": "reference"
    },
    {
      "relativePath": "wiki/analyses/podium-frontend-deploy-cosmetics.md",
      "label": "Frontend deploy hazard",
      "appliesTo": "web/frontend/",
      "mode": "reference"
    }
  ],
  "promptAdvisories": [
    "Treat this repo as live infrastructure. Do not read /home/james/symphony-host.env; do not print secrets.",
    "Ask James before service restarts/stops, systemd unit edits, Plane mutations, smoke requeues, env edits, destructive data actions, or live deploys.",
    "For Symphony-specific questions, read wiki/index.md then wiki/ROUTING.md before broad search.",
    "For frontend work, do not use automatic Playwright/e2e as an edit gate; it is manual and may affect .next.",
    "Before commit/push, inspect diff for secrets and run relevant advisory checks."
  ],
  "gitReminder": {
    "enabled": true,
    "posture": "advisory",
    "text": "Before git commit/push: inspect diff, ensure no secrets, run git diff --check. Run uv run pytest -q manually for Python changes and pnpm exec tsc --noEmit for frontend changes when relevant; Playwright stays manual for UI flows."
  },
  "gitPreflight": {
    "enabled": true,
    "posture": "advisory",
    "text": "Before git commit/push: inspect diff, ensure no secrets, run git diff --check. Run uv run pytest -q manually for Python changes and pnpm exec tsc --noEmit for frontend changes when relevant; Playwright stays manual for UI flows.",
    "runProjectChecks": true
  },
  "smokeTests": {
    "loadSmoke": true,
    "isolatedLoadSmoke": true,
    "syntaxDryChecks": [
      "python-py-compile",
      "json-jq",
      "javascript-node-check",
      "shell-bash-n"
    ],
    "safetyDryChecks": [
      "benign-pass",
      "destructive-db-log-rm",
      "generic-rm-rf",
      "live-systemctl",
      "secret-env-bash-read",
      "secret-env-read",
      "secret-env-write",
      "symlink-escape"
    ],
    "projectCheckDryChecks": [
      "mocked-beforeGit-agentEnd-root-resolution"
    ],
    "manualScenarioListing": true,
    "guidanceDry": true
  },
  "skipped": [
    {
      "area": "formatters",
      "reason": "No repo-declared formatter contract; automatic formatting would be surprising."
    },
    {
      "area": "prettier/biome/black/shfmt",
      "reason": "Tools not detected in PATH or repo-local bins."
    },
    {
      "area": "typescript per-file syntax",
      "reason": "TS/TSX requires project context; covered by deferred tsc advisory."
    },
    {
      "area": "frontend-next-build automatic check",
      "reason": "next build can mutate live .next; use deploy.sh/manual flow intentionally."
    },
    {
      "area": "Playwright auto-run",
      "reason": "Expensive and can affect .next; manual listing only."
    },
    {
      "area": "YAML/TOML syntax",
      "reason": "No installed parser found in probe."
    },
    {
      "area": "unsupported write tools",
      "reason": "Bash commands can mutate files without exposing exact touched file paths; harness blocks known dangerous commands only."
    },
    {
      "area": "touched-file guidance full injection",
      "reason": "All guidance is reference-mode architecture guidance to avoid dumping large docs into prompts."
    },
    {
      "area": "python-pytest automatic beforeGit",
      "reason": "Full pytest suite is too slow for every git attempt; kept as manual advisory in git reminder."
    },
    {
      "area": "ignored .rpiv profile source",
      "reason": "Tracked copy now lives at wiki/raw/personal-harness-pi-profile.md; local .rpiv artifact remains skill output."
    }
  ]
};

const MSG_GUIDANCE = "personal-harness/guidance";
const MSG_GIT = "personal-harness/git";
const MSG_PROJECT = "personal-harness/project-check";
const MSG_SCENARIO = "personal-harness/scenario";
const MSG_SAFETY = "personal-harness/safety";
const WRITE_TOOLS = new Set(["write", "edit", "ast_grep_replace"]);
const TOUCH_TOOLS = new Set(["read", "write", "edit", "ast_grep_replace"]);
const injectedGuidance = new Set<string>();
const analyzedStates = new Set<string>();
// Touched-file tracking for this user prompt (drives agentEnd / beforeGit project + scenario checks).
const touchedRelPaths = new Set<string>();
const touchedExtensions = new Set<string>();

export default function personalHarness(pi: ExtensionAPI): void {
  registerPersonalHarness(pi);
}

function harnessRoot(cwd: string): string {
  const target = PROFILE.targetRepo;
  if (!target) return cwd;
  const rel = relative(target, cwd);
  return rel === "" || (!rel.startsWith("..") && !isAbsolute(rel)) ? target : cwd;
}

function registerPersonalHarness(pi: ExtensionAPI): void {
  pi.on("session_start", async (_event, ctx) => onSessionStart(ctx, pi));
  pi.on("session_compact", async (_event, ctx) => onSessionCompact(ctx, pi));
  pi.on("agent_start", async (_event, _ctx) => {
    touchedRelPaths.clear();
    touchedExtensions.clear();
  });
  pi.on("tool_call", async (event, ctx) => onToolCall(event, ctx, pi));
  // tool_result overloads vary across Pi versions; keep generated extension self-contained.
  (pi as any).on("tool_result", async (event: any, ctx: any) => onToolResult(event, ctx, pi));
  pi.on("before_agent_start", async (event) => onBeforeAgentStart(event));
  pi.on("agent_end", async (_event, ctx) => onAgentEnd(ctx, pi));
}

async function onSessionStart(ctx: { cwd: string }, pi: ExtensionAPI): Promise<void> {
  const root = harnessRoot(ctx.cwd);
  injectedGuidance.clear();
  analyzedStates.clear();
  touchedRelPaths.clear();
  touchedExtensions.clear();
  injectRootGuidance(root, pi);
}

async function onSessionCompact(ctx: { cwd: string }, pi: ExtensionAPI): Promise<void> {
  const root = harnessRoot(ctx.cwd);
  injectedGuidance.clear();
  analyzedStates.clear();
  injectRootGuidance(root, pi);
}

async function onBeforeAgentStart(event: { systemPrompt: string }): Promise<{ systemPrompt: string } | undefined> {
  const content = buildPromptAdvisory();
  if (!content) return undefined;
  return {
    systemPrompt: `${event.systemPrompt}\n\n${content}`,
  };
}

async function onAgentEnd(ctx: { cwd: string; hasUI?: boolean; ui?: any }, pi: ExtensionAPI): Promise<void> {
  const root = harnessRoot(ctx.cwd);
  // agent_end CANNOT block. Run agentEnd project checks and surface failures as advisory only.
  const failures = await runProjectChecksForTiming("agentEnd", root, pi);
  for (const failure of failures) {
    pi.sendMessage({
      customType: MSG_PROJECT,
      content: formatAdvisoryFailure(`project check (agentEnd, ${failure.spec.posture === "blocking" ? "blocking-requested→advisory" : "advisory"})`, failure.spec.id, failure.spec.cwd || ".", failure.result),
      display: true,
    });
  }
  // Surface manual scenario checks whose triggers were touched — listed, never executed.
  for (const spec of PROFILE.scenarioChecks) {
    if (spec.timing !== "manual") continue;
    if (!checkTriggered(spec)) continue;
    pi.sendMessage({
      customType: MSG_SCENARIO,
      content: formatScenarioAdvisory(spec),
      display: true,
    });
  }
  if (ctx.hasUI && ctx.ui) ctx.ui.setStatus("personal-harness", undefined);
}

async function onToolCall(event: { toolName: string; input: Record<string, unknown> }, ctx: { cwd: string }, pi: ExtensionAPI) {
  const root = harnessRoot(ctx.cwd);
  // 1. Safety blockers run FIRST, before guidance injection and git handling — fail fast, deterministic.
  const safety = checkSafetyRules(event.toolName, event.input, ctx.cwd, root);
  if (safety) {
    if (safety.posture === "blocking") {
      return { block: true, reason: safety.reason };
    }
    pi.sendMessage({ customType: MSG_SAFETY, content: safety.reason, display: true });
  }

  if (TOUCH_TOOLS.has(event.toolName)) {
    injectTouchedGuidance(event, ctx.cwd, root, pi);
  }

  if (isGitCommitOrPushAttempt(event.toolName, event.input)) {
    // 2. beforeGit project + scenario checks run BEFORE any git reminder; blocking posture can block here.
    if (PROFILE.gitPreflight.runProjectChecks) {
      const blocked = await runBeforeGitBlockingChecks(root, pi);
      if (blocked) return { block: true, reason: blocked };
    }
    if (PROFILE.gitReminder.enabled) {
      if (PROFILE.gitReminder.posture === "blocking") {
        return { block: true, reason: PROFILE.gitReminder.text };
      }
      pi.sendMessage({ customType: MSG_GIT, content: PROFILE.gitReminder.text, display: false });
    }
  }
}

async function onToolResult(event: { toolCallId?: string; toolName: string; input: Record<string, unknown>; content?: Array<{ type: string; text?: string }>; isError?: boolean }, ctx: { cwd: string }, pi: ExtensionAPI) {
  const root = harnessRoot(ctx.cwd);
  if (!isWriteResultTool(event.toolName, event.input)) return;
  if (event.isError) return;

  const filePaths = resolveTouchedPaths(event.input, ctx.cwd).filter(
    (filePath) => existsSync(filePath) && isRegularFile(filePath) && isInsideProject(filePath, root) && !isExternalOrVendor(filePath, root),
  );
  if (filePaths.length === 0) return;

  // Track touched files/extensions so agentEnd/beforeGit checks only run when relevant.
  for (const filePath of filePaths) {
    const rel = relative(root, filePath).split(sep).join("/");
    touchedRelPaths.add(rel);
    const dot = rel.lastIndexOf(".");
    if (dot >= 0) touchedExtensions.add(rel.slice(dot));
  }

  const originalContent = Array.isArray(event.content) ? event.content : [];
  const notices: string[] = [];

  for (const filePath of filePaths) {
    const stateKey = buildStateKey(event.toolCallId, filePath);
    if (analyzedStates.has(stateKey)) continue;
    analyzedStates.add(stateKey);

    const syntaxFailure = await firstSyntaxFailure(pi, filePath, root);
    if (syntaxFailure) {
      return {
        content: [...originalContent, { type: "text", text: formatBlockingFailure("syntax", syntaxFailure.spec.id, filePath, syntaxFailure.result) }],
        isError: true,
      };
    }

    let formatterRan = false;
    for (const spec of matchingSpecs(PROFILE.formatters, filePath)) {
      const result = await runSpec(pi, spec, filePath, root);
      if (result.ok) formatterRan = true;
      if (!result.ok) {
        notices.push(formatAdvisoryFailure("formatter", spec.id, filePath, result));
      }
    }

    if (formatterRan) {
      const postFormatSyntaxFailure = await firstSyntaxFailure(pi, filePath, root);
      if (postFormatSyntaxFailure) {
        return {
          content: [...originalContent, { type: "text", text: formatBlockingFailure("post-format syntax", postFormatSyntaxFailure.spec.id, filePath, postFormatSyntaxFailure.result) }],
          isError: true,
        };
      }
    }

    for (const spec of matchingSpecs(PROFILE.lintChecks, filePath)) {
      const result = await runSpec(pi, spec, filePath, root);
      if (!result.ok && spec.posture === "blocking") {
        return {
          content: [...originalContent, { type: "text", text: formatBlockingFailure("lint", spec.id, filePath, result) }],
          isError: true,
        };
      }
      if (!result.ok) {
        notices.push(formatAdvisoryFailure("lint", spec.id, filePath, result));
      }
    }

    if (existsSync(filePath)) analyzedStates.add(buildStateKey(event.toolCallId, filePath));
  }

  // afterWrite project checks: blocking posture patches the write result as failed; advisory adds a notice.
  for (const spec of PROFILE.projectChecks) {
    if (spec.timing !== "afterWrite") continue;
    if (!specTriggeredByPaths(spec, filePaths, root)) continue;
    const result = await runProjectSpec(pi, spec, root);
    if (!result.ok && spec.posture === "blocking") {
      return {
        content: [...originalContent, { type: "text", text: formatBlockingFailure("project check", spec.id, spec.cwd || ".", result) }],
        isError: true,
      };
    }
    if (!result.ok) {
      notices.push(formatAdvisoryFailure("project check", spec.id, spec.cwd || ".", result));
    }
  }

  if (notices.length === 0) return;
  return {
    content: [...originalContent, { type: "text", text: notices.join("\n\n") }],
  };
}

// ---------------------------------------------------------------------------
// Safety blockers (deterministic; no model/web/UI calls).
// ---------------------------------------------------------------------------

// Trusted-loop opt-in for in-worker live verification. Honored ONLY when the
// process was spawned by the Ralph loop (RALPH_LOOP_TRUSTED=1) AND the command
// is a bare, anchored `systemctl restart symphony-host(.service)` — restart
// only, that single unit only, no command chaining or extra arguments. Any
// stop/start/reload, any other unit, or any `&&`/`;`/`|` chaining fails the
// anchor and stays blocked. Interactive operator sessions (env unset) always
// hit the gate.
function allowTrustedSymphonyRestart(command: string): boolean {
  if (process.env.RALPH_LOOP_TRUSTED !== "1") return false;
  return /^\s*(sudo\s+)?systemctl\s+restart\s+symphony-host(\.service)?\s*$/.test(command.trim());
}

function checkSafetyRules(toolName: string, input: Record<string, unknown>, cwd: string, root: string = harnessRoot(cwd)): { reason: string; posture: "blocking" | "advisory" } | undefined {
  for (const rule of PROFILE.safetyRules) {
    if (!rule.tools.includes(toolName)) continue;

    if (toolName === "bash") {
      const command = readBashCommand(input);
      if (command && rule.match && safeRegex(rule.match)?.test(command)) {
        // Narrow trusted-loop exception: a Ralph loop worker may restart ONLY
        // symphony-host.service (for in-worker live verification). stop/start/
        // reload, other units, chaining, and interactive sessions stay blocked.
        if (rule.id === "live-systemctl" && allowTrustedSymphonyRestart(command)) {
          continue;
        }
        return { reason: formatSafetyReason(rule, command), posture: rule.posture };
      }
      continue;
    }

    if (toolName === "ast_grep_replace" && input.apply !== true) continue;
    const paths = resolveTouchedPaths(input, cwd);
    for (const filePath of paths) {
      if (pathMatchesSafetyRule(rule, filePath, root)) {
        return { reason: formatSafetyReason(rule, relative(root, filePath).split(sep).join("/")), posture: rule.posture };
      }
    }
  }
  return undefined;
}

function pathMatchesSafetyRule(rule: SafetyRuleSpec, filePath: string, cwd: string): boolean {
  if (!rule.paths || rule.paths.length === 0) return false;
  // Resolve symlinks for existing paths; for new writes, resolve the deepest existing ancestor.
  const resolved = hardenedResolve(filePath);
  const root = hardenedResolve(cwd);
  // Block any symlink escape outside the project root for write-capable tools.
  if (rule.tools.some((t) => WRITE_TOOLS.has(t)) && !isInsideResolved(resolved, root)) {
    return true;
  }
  const rel = relative(root, resolved).split(sep).join("/");
  const relRaw = relative(cwd, filePath).split(sep).join("/");
  return rule.paths.some((pattern) => globMatch(pattern, rel) || globMatch(pattern, relRaw));
}

// Resolve the realpath of the deepest existing ancestor, then re-append the missing tail.
// This catches new-file writes through a symlinked parent directory.
function hardenedResolve(target: string): string {
  let current = resolve(target);
  const tail: string[] = [];
  // Walk up until an existing path is found.
  // Bounded by filesystem depth; the loop terminates at the root.
  // eslint-disable-next-line no-constant-condition
  while (true) {
    if (existsSync(current)) {
      try {
        const real = realpathSync(current);
        return tail.length ? join(real, ...tail.reverse()) : real;
      } catch {
        return tail.length ? join(current, ...tail.reverse()) : current;
      }
    }
    const parent = dirname(current);
    if (parent === current) return target; // reached root, nothing existed
    tail.push(current.slice(parent.length + 1));
    current = parent;
  }
}

function isInsideResolved(resolvedPath: string, resolvedRoot: string): boolean {
  const rel = relative(resolvedRoot, resolvedPath);
  return rel === "" || (!rel.startsWith("..") && !isAbsolute(rel));
}

function safeRegex(pattern: string): RegExp | undefined {
  try {
    return new RegExp(pattern);
  } catch {
    return undefined;
  }
}

// Minimal glob: supports ** (any path), * (any non-separator run), and literal segments.
function globMatch(pattern: string, candidate: string): boolean {
  const normalized = pattern.replace(/^\.\//, "").replace(/\/$/, "");
  const specials = ".+^${}()|[]\\";
  let out = "";
  for (let i = 0; i < normalized.length; i++) {
    const ch = normalized[i];
    if (ch === "*") {
      if (normalized[i + 1] === "*") {
        out += ".*";
        i++;
      } else {
        out += "[^/]*";
      }
    } else if (specials.includes(ch)) {
      out += `\\${ch}`;
    } else {
      out += ch;
    }
  }
  const regex = safeRegex(`^${out}(?:/.*)?$`);
  return regex ? regex.test(candidate) : candidate === normalized;
}

function readBashCommand(input: unknown): string {
  if (!input || typeof input !== "object") return "";
  const raw = input as { command?: unknown; cmd?: unknown };
  return typeof raw.command === "string" ? raw.command : typeof raw.cmd === "string" ? raw.cmd : "";
}

function formatSafetyReason(rule: SafetyRuleSpec, subject: string): string {
  return `personal-harness safety: ${rule.operation} blocked (${rule.id}). ${rule.reason} [${subject}]`;
}

// ---------------------------------------------------------------------------
// Deferred project + scenario checks.
// ---------------------------------------------------------------------------

async function runProjectChecksForTiming(timing: CheckTiming, cwd: string, pi: ExtensionAPI): Promise<Array<{ spec: ProjectCheckSpec; result: CommandResult }>> {
  const failures: Array<{ spec: ProjectCheckSpec; result: CommandResult }> = [];
  for (const spec of PROFILE.projectChecks) {
    if (spec.timing !== timing) continue;
    if (!checkTriggered(spec)) continue;
    const result = await runProjectSpec(pi, spec, cwd);
    if (!result.ok) failures.push({ spec, result });
  }
  return failures;
}

async function runBeforeGitBlockingChecks(cwd: string, pi: ExtensionAPI): Promise<string | undefined> {
  // Project checks first, then non-manual scenario checks; both honor blocking posture here.
  const specs: ProjectCheckSpec[] = [
    ...PROFILE.projectChecks.filter((s) => s.timing === "beforeGit"),
    ...PROFILE.scenarioChecks.filter((s) => s.timing === "beforeGit"),
  ];
  const blockers: string[] = [];
  for (const spec of specs) {
    if (!checkTriggered(spec)) continue;
    const result = await runProjectSpec(pi, spec, cwd);
    if (result.ok) continue;
    if (spec.posture === "blocking") {
      blockers.push(formatBlockingFailure("pre-git check", spec.id, spec.cwd || ".", result));
    } else {
      pi.sendMessage({ customType: MSG_PROJECT, content: formatAdvisoryFailure("pre-git check", spec.id, spec.cwd || ".", result), display: true });
    }
  }
  return blockers.length ? blockers.join("\n\n") : undefined;
}

// Triggered when no triggers are configured (always at its timing) OR a touched extension/glob matched.
function checkTriggered(spec: ProjectCheckSpec): boolean {
  const hasTriggers = spec.triggerExtensions.length > 0 || spec.triggerGlobs.length > 0;
  if (!hasTriggers) return true;
  for (const ext of spec.triggerExtensions) {
    if (touchedExtensions.has(ext)) return true;
  }
  for (const glob of spec.triggerGlobs) {
    for (const rel of touchedRelPaths) {
      if (globMatch(glob, rel)) return true;
    }
  }
  return false;
}

function specTriggeredByPaths(spec: ProjectCheckSpec, filePaths: string[], cwd: string): boolean {
  const hasTriggers = spec.triggerExtensions.length > 0 || spec.triggerGlobs.length > 0;
  if (!hasTriggers) return true;
  for (const filePath of filePaths) {
    const rel = relative(cwd, filePath).split(sep).join("/");
    const dot = rel.lastIndexOf(".");
    const ext = dot >= 0 ? rel.slice(dot) : "";
    if (ext && spec.triggerExtensions.includes(ext)) return true;
    if (spec.triggerGlobs.some((glob) => globMatch(glob, rel))) return true;
  }
  return false;
}

async function runProjectSpec(pi: ExtensionAPI, spec: ProjectCheckSpec, cwd: string): Promise<CommandResult> {
  const specCwd = spec.cwd ? resolve(cwd, spec.cwd) : cwd;
  try {
    const result = await pi.exec(spec.command, spec.args, { cwd: specCwd, timeout: spec.timeoutMs });
    const code = typeof (result as { code?: unknown }).code === "number" ? (result as { code: number }).code : 0;
    const killed = Boolean((result as { killed?: unknown }).killed);
    return {
      ok: code === 0 && !killed,
      stdout: result.stdout ?? "",
      stderr: result.stderr ?? "",
      error: code === 0 && !killed ? undefined : `exit code ${code}${killed ? " (killed)" : ""}`,
    };
  } catch (error) {
    const anyError = error as { stdout?: string; stderr?: string; message?: string };
    return { ok: false, stdout: anyError.stdout ?? "", stderr: anyError.stderr ?? "", error: anyError.message ?? String(error) };
  }
}

function formatScenarioAdvisory(spec: ScenarioCheckSpec): string {
  const cmd = [spec.command, ...spec.args].join(" ");
  return [
    `personal-harness scenario check available (manual — NOT auto-run): ${spec.id}`,
    `Run when ready: (cd ${spec.cwd || "."} && ${cmd})`,
    spec.reason,
  ].filter(Boolean).join("\n");
}

// ---------------------------------------------------------------------------
// Existing per-file syntax / formatter / lint pipeline.
// ---------------------------------------------------------------------------

function isWriteResultTool(toolName: string, input: Record<string, unknown>): boolean {
  if (!WRITE_TOOLS.has(toolName)) return false;
  if (toolName === "ast_grep_replace") return input.apply === true;
  return true;
}

function resolveTouchedPaths(input: Record<string, unknown>, cwd: string): string[] {
  const paths: string[] = [];
  const raw = input.file_path ?? input.path;
  if (typeof raw === "string" && raw.length > 0) paths.push(resolveMaybeRelative(raw, cwd));

  const rawPaths = input.paths;
  if (Array.isArray(rawPaths)) {
    for (const item of rawPaths) {
      if (typeof item === "string" && item.length > 0) paths.push(resolveMaybeRelative(item, cwd));
    }
  }

  return [...new Set(paths)];
}

function resolveMaybeRelative(filePath: string, cwd: string): string {
  return isAbsolute(filePath) ? filePath : resolve(cwd, filePath);
}

async function firstSyntaxFailure(pi: ExtensionAPI, filePath: string, cwd: string): Promise<{ spec: SyntaxSpec; result: CommandResult } | undefined> {
  for (const spec of matchingSpecs(PROFILE.syntaxChecks, filePath)) {
    const result = await runSpec(pi, spec, filePath, cwd);
    if (!result.ok) return { spec, result };
  }
}

function buildStateKey(toolCallId: string | undefined, filePath: string): string {
  const stat = statSync(filePath);
  return `${toolCallId ?? "unknown"}:${filePath}:${stat.mtimeMs}:${stat.size}`;
}

function isRegularFile(filePath: string): boolean {
  try {
    return statSync(filePath).isFile();
  } catch {
    return false;
  }
}

function isInsideProject(filePath: string, cwd: string): boolean {
  const rel = relative(cwd, filePath);
  return rel === "" || (!rel.startsWith("..") && !isAbsolute(rel));
}

function isExternalOrVendor(filePath: string, cwd: string): boolean {
  if (!isInsideProject(filePath, cwd)) return true;
  const rel = relative(cwd, filePath).split(sep).join("/");
  return rel.includes("/node_modules/") || rel.startsWith("node_modules/") || rel.includes("/.git/") || rel.startsWith(".git/");
}

function matchingSpecs<T extends CommandSpec>(specs: readonly T[], filePath: string): T[] {
  return specs.filter((spec) => spec.extensions.some((ext) => filePath.endsWith(ext)));
}

async function runSpec(pi: ExtensionAPI, spec: CommandSpec, filePath: string, cwd: string): Promise<CommandResult> {
  const args = spec.args.map((arg) => (arg === "{file}" ? filePath : arg));
  try {
    const result = await pi.exec(spec.command, args, { cwd, timeout: spec.timeoutMs });
    const code = typeof (result as { code?: unknown }).code === "number" ? (result as { code: number }).code : 0;
    const killed = Boolean((result as { killed?: unknown }).killed);
    return {
      ok: code === 0 && !killed,
      stdout: result.stdout ?? "",
      stderr: result.stderr ?? "",
      error: code === 0 && !killed ? undefined : `exit code ${code}${killed ? " (killed)" : ""}`,
    };
  } catch (error) {
    const anyError = error as { stdout?: string; stderr?: string; message?: string };
    return {
      ok: false,
      stdout: anyError.stdout ?? "",
      stderr: anyError.stderr ?? "",
      error: anyError.message ?? String(error),
    };
  }
}

function formatBlockingFailure(kind: string, id: string, filePath: string, result: { stdout: string; stderr: string; error?: string }): string {
  const details = [result.stderr, result.stdout, result.error].filter(Boolean).join("\n").trim();
  return [`personal-harness ${kind} check failed: ${id}`, `Location: ${filePath}`, details].filter(Boolean).join("\n");
}

function formatAdvisoryFailure(kind: string, id: string, filePath: string, result: { stdout: string; stderr: string; error?: string }): string {
  const details = [result.stderr, result.stdout, result.error].filter(Boolean).join("\n").trim();
  return [`personal-harness ${kind} advisory: ${id} did not complete.`, `Location: ${filePath}`, details].filter(Boolean).join("\n");
}

function buildPromptAdvisory(): string {
  if (PROFILE.promptAdvisories.length === 0) return "";
  // Reference-only pointers to architecture docs are listed here so the model can read them on demand
  // instead of dumping large doc content into every prompt. Full/scoped guidance is injected separately.
  const refs = PROFILE.architectureGuidance
    .filter((g) => g.mode === "reference")
    .map((g) => `- ${g.label}: ${g.relativePath}`);
  const lines = ["## Personal Harness Advisory", ...PROFILE.promptAdvisories.map((item) => `- ${item}`)];
  if (refs.length) {
    lines.push("", "Architecture references (read with the read tool only when relevant):", ...refs);
  }
  return lines.join("\n");
}

function isGitCommitOrPushAttempt(toolName: string, input: unknown): boolean {
  if (toolName !== "bash") return false;
  const command = readBashCommand(input);
  return /(^|\s|&&|;|\|)git\s+(commit|push)(\s|$)/i.test(command);
}

// ---------------------------------------------------------------------------
// Guidance injection (touched-file + architecture).
// ---------------------------------------------------------------------------

function injectRootGuidance(cwd: string, pi: ExtensionAPI): void {
  for (const spec of PROFILE.guidanceFiles.filter((item) => item.appliesTo === "" || item.appliesTo === ".")) {
    injectGuidanceFile(cwd, spec.relativePath, spec.label, "auto-loaded at session start", "full", pi);
  }
  for (const spec of PROFILE.architectureGuidance.filter((item) => item.appliesTo === "" || item.appliesTo === ".")) {
    if (spec.mode === "scoped") continue; // scoped entries inject only on touch
    injectGuidanceFile(cwd, spec.relativePath, spec.label, "auto-loaded at session start", spec.mode, pi);
  }
}

function injectTouchedGuidance(event: { toolName: string; input: Record<string, unknown> }, cwd: string, root: string, pi: ExtensionAPI): void {
  for (const touched of resolveTouchedPaths(event.input, cwd)) {
    if (!isInsideProject(touched, root)) continue;
    const relTouched = relative(root, touched).split(sep).join("/");
    for (const spec of PROFILE.guidanceFiles) {
      const appliesTo = spec.appliesTo.replace(/^\.\//, "").replace(/\/$/, "");
      if (appliesTo && relTouched !== appliesTo && !relTouched.startsWith(`${appliesTo}/`)) continue;
      injectGuidanceFile(root, spec.relativePath, spec.label, `auto-loaded because ${event.toolName} touched ${relTouched}`, "full", pi);
    }
    for (const spec of PROFILE.architectureGuidance) {
      const appliesTo = spec.appliesTo.replace(/^\.\//, "").replace(/\/$/, "");
      if (!appliesTo) continue; // root entries handled at session start
      if (relTouched !== appliesTo && !relTouched.startsWith(`${appliesTo}/`)) continue;
      injectGuidanceFile(root, spec.relativePath, spec.label, `auto-loaded because ${event.toolName} touched ${relTouched}`, spec.mode, pi);
    }
  }
}

function injectGuidanceFile(cwd: string, relativePath: string, label: string, trigger: string, mode: "full" | "reference" | "scoped", pi: ExtensionAPI): void {
  const key = relativePath.split(sep).join("/");
  if (injectedGuidance.has(key)) return;
  const absolute = join(cwd, relativePath);
  if (!isInsideProject(absolute, cwd)) return;
  if (!existsSync(absolute)) return;
  injectedGuidance.add(key);
  if (mode === "reference") {
    // Reference-only: point at the doc, do not dump its content.
    pi.sendMessage({
      customType: MSG_GUIDANCE,
      content: [
        `[personal-harness guidance — reference material, NOT a task. ${trigger}.`,
        `Read ${relativePath} with the read tool only if directly relevant to the current request.]`,
        "",
        `## Personal Harness Guidance: ${label} (reference) → ${relativePath}`,
      ].join("\n"),
      display: shouldDisplayDebug(pi),
    });
    return;
  }
  const content = readFileSync(absolute, "utf-8");
  pi.sendMessage({
    customType: MSG_GUIDANCE,
    content: wrapGuidance(label, content, trigger),
    display: shouldDisplayDebug(pi),
  });
}

function shouldDisplayDebug(pi: ExtensionAPI): boolean {
  return Boolean((pi as unknown as { getFlag?: (name: string) => unknown }).getFlag?.("debug"));
}

function wrapGuidance(label: string, content: string, trigger: string): string {
  return [
    `[personal-harness guidance — reference material, NOT a task. ${trigger}.`,
    "Consult only if directly relevant to the user's current request; otherwise ignore.]",
    "",
    `## Personal Harness Guidance: ${label}`,
    "",
    content,
  ].join("\n");
}
